sudo: required
language: node_js
node_js:
- 6
- 7
cache:
  directories:
  - node_modules

# before_script:
# - npm run -s lint
# - npm run -s build
script: npm run -s build

deploy:
  provider: npm
  email: mdakram28@gmail.com